slider1:
  name: Ref. Hora - Ligar
  icon: mdi:timer
  initial: 21
  min: 0
  max: 23
  step: 1 
  
slid_minuto_liga:
  name: Ref. Minuto - Ligar
  icon: mdi:timer
  initial: 0
  min: 0
  max: 59
  step: 1 
  
slid_hora_desliga:
  name: Ref. Hora - Desligar
  icon: mdi:timer
  initial: 6
  min: 0
  max: 23
  step: 1 
  
slid_minuto_desliga:
  name: Ref. Minuto - Desligar
  icon: mdi:timer
  initial: 45
  min: 0
  max: 59
  step: 1 
  
slid_tempo_acoes:
  name: Tempo entre Acoes
  icon: mdi:timer
  initial: 5
  min: 1
  max: 30
  step: 1
  
slid_hora_liga_fundo:
  name: Ref. Hora - Ligar
  icon: mdi:timer
  initial: 20
  min: 0
  max: 23
  step: 1 
  
slid_minuto_liga_fundo:
  name: Ref. Minuto - Ligar
  icon: mdi:timer
  initial: 0
  min: 0
  max: 59
  step: 1 
  
slid_hora_desliga_fundo:
  name: Ref. Hora - Desligar
  icon: mdi:timer
  initial: 22
  min: 0
  max: 23
  step: 1 
  
slid_minuto_desliga_fundo:
  name: Ref. Minuto - Desligar
  icon: mdi:timer
  initial: 0
  min: 0
  max: 59
  step: 1
  
slid_hora_desliga_tv:
  name: Ref. Hora - Desligar
  icon: mdi:timer
  initial: 6
  min: 0
  max: 23
  step: 1 
  
slid_minuto_desliga_tv:
  name: Ref. Minuto - Desligar
  icon: mdi:timer
  initial: 50
  min: 0
  max: 59
  step: 1
  
slid_hora_liga_tv:
  name: Ref. Hora - Ligar
  icon: mdi:timer
  initial: 6
  min: 0
  max: 23
  step: 1 
  
slid_minuto_liga_tv:
  name: Ref. Minuto - Ligar
  icon: mdi:timer
  initial: 15
  min: 0
  max: 59
  step: 1