- platform: broadlink
  host: 192.168.2.67
  mac: '34:EA:34:B2:EB:E7'
  type: rm_mini
  timeout: 5
  switches:
    tv_lg_mais:
      friendly_name: LGV+
      command_on: 'JgBQAAABI5MRFBETEjcSExITERQRExITEjcSNxITETgSNxI3EjcSNxITETgRFBETEhMSExEUERMROBITEjcSNxI3EjcSNxI3EgAFDwABI0oRAA0FAAAAAAAAAAA=='   
    tv_lg_menos:
      friendly_name: LGV-
      command_on: 'JgBQAAABI5MRExITEjcSExEUERMSExITETgSNxITETgROBE4ETgSNxI3EjcSExEUERMSExITERQRExITEjcSNxI3EjcSNxI3EgAFDwABI0oRAA0FAAAAAAAAAAA=='
    tv_lg_liga:
      friendly_name: LGLD
      command_on: 'JgBYAAABI5ISExMSEjcTEhAWDxQTEhITEDkROBITDzoROBI3EjcQORAVERQPFhA4ERQRFBITEhITNhI3ETgQFRI3EjcSNxI3EgAFDwABIksRAAw1AAEjShAADQU='
      command_off: 'JgBYAAABI5ITEhMSETgRFBAVERMTEhITEDkSNxITDzoQORI3EjcQORAVERQPFRE4ERQRFBEUEhITNhM2EzcRFBI3EzYSNxM2EwAFDgABJEkQAAw2AAEjShIADQU=='
    num_1:
      friendly_name: Num 1
      command_on: 'JgBgAAABKJUSOREUEhMSOBM3EhUQFBITEhMSOBM4EhMSExM3EjkRORM3EhMTExEUEhMTEhITEhMSFBI4EjgSOBM4EjgSOBI5EQAFDwABKEoTAAxPAAEoSxIADE8AAShKEgANBQAAAAAAAAAA='
    num_2:
      friendly_name: Num 2
      command_on: 'JgBgAAABKZQSOBITEhMSORM3EhMSExITEhQSOBI4ExISFBE5EzcSOBIUERQSOBITEjgSExIUEhMSOBI4EhMSORMSEjgSOBM4EgAFDgABKEoSAAxQAAEpSRIADFAAAShKEwANBQAAAAAAAAAA='
    num_3:
      friendly_name: Num 3
      command_on: 'JgBaAEAGBQXYlxA7ChoQFRA6EDsQFRATExcLGA08EDwQFg4VETkQOhE6ERMROREVERQSFQ8UERcPFBA7EBQQOxA6DzkRQAw7DzsQAAUOAAEnTRAADFAAASdMEAANBQAAAAAAAAAAAAAAAAAA=='
    num_4:
      friendly_name: Num 4
      command_on: 'JgBgAAABKZQSOBMTERQSOBI4ExITExETEhQROhE5ERMSFBE6EDgTOBMTEhMRFBIUEhMQFRETExMRORI4ETkSOhE4EjgSOBI5EgAFDQABKEsSAAxPAAEpShEADFIAAShKEgANBQAAAAAAAAAA=='
    num_5:
      friendly_name: Num 5
      command_on: 'JgBmAAABJ5YQOxAUERMSORE6DRkQFREUEBQQOxA9DhQRFRA5EjkROhE5EBUQOhEWDxUQExIVEBYPFRE5ERQROhE6EDkSORA7EAAFEF0FBQYgBgULhFEKAAxVAAEoSxIADFAAASlKEQANBQAA=='
    num_6:
      friendly_name: Num 6
      command_on: 'JgBgAAABKJUTNxMUERMTNxM3ExMSExITEhMSOBI5EhMTEhI4EjkSOBIUEjgRORIUEhMRFBEUERUROBMSEhQRORE5EjgSORE5EgAFDgABKUoSAAxRAAEpShIADFAAASlKEwANBQAAAAAAAAAA=='
    num_7:
      friendly_name: Num 7
      command_on: 'JgBgAAABKZQTOBEUEhMSOBM4ERQSExMSEhMSORI4EhMSExI5EjgTOBEUEhMSOBITExMSExITEhMSORE5ExISORI4EzcTOBI4EgAFEAABKEoSAAxTAAEoSxIADFEAAShLEgANBQAAAAAAAAAA=='
    num_8:
      friendly_name: Num 8
      command_on: 'JgBgAAABKZQSOBIUERQRORI4EhMSFBITERQSOBI4ExITEhI5EjgSOBM3EhQSExI4EhMSExITEhMTExE5EjgSExI4EjkSOBI4EwAFDQABJ0sSAAxPAAEoShIADE8AAShLEwANBQAAAAAAAAAA=='
    num_9:
      friendly_name: Num 9
      command_on: 'JgBgAAABKJUSOBMTERUROBI4EhMSFBIUEBUROBI5ERQRFRE4EjgSOREVETgSFBI4ERQRFRAVERQRNhUSEjkSExI5ETkRORI4EgAFDgABKEoSAAxPAAEpShIADFEAASdLEQANBQAAAAAAAAAA=='
    num_0:
      friendly_name: Num 0
      command_on: 'JgBgAAABKZUSOBMSExISORI4EhQTERITEhQSOBM3EhMSFBE5EjgSOBI5EhMSOBI4ExMSFBETEhQRExI4ExMRFBI4EzcTOBE5EgAFDgABKEsSAAxPAAEpShIADFAAASlKEQANBQAAAAAAAAAA=='
    controle_canal:
      friendly_name: Controle Canal
      command_on: 'JgBgAAABKJYRORITEhMSORI4ExISExIUEhMSOBI5EhMSExM3EjkSOBITEhMSORM3FBESFBEUExISOBM4EhQRExI4EzgTNxI4EwAFDQABK0oTAAxSAAEoSxIADFIAAShLEwANBQAAAAAAAAAA=='
      command_off: 'JgBoAAABKZQSOBMTExITNxI5ERQSExIUEhISORE5EhMSExI5EjgSOBM4ERQSExMSEjgSFBITExISExI4EjkSOBIUEjgSOBI4EwAFDgABKUkTAAxRAAEpSRIADFEAAShLEgAMUAABKEsSAA0F=='
    controle_volume:
      friendly_name: Controle Volume
      command_on: 'JgBoAAABKZQTNxITEhMSORI4EhMTEhMSEhQSOBM3EhMSExM4EjgTNxITExMRFBITEjgSExIUEhMSOBI4EjcUOBMSEjgSORI4EwAFDgABKEoTAAxQAAEpShMADE8AASlKEQAMUQABKEoSAA0F=='
      command_off: 'JgBoAAABKZQSORITEhQROBI5EhMSFBETEhQRORI4ExISExI5EzcSOBI5EhMSFBE4EzgSExITExITExM3EzcSExIVEDkTNxM4EgAFDwABKEsRAAxUAAEpShIADFQAAShLEgAMUwABKUkSAA0F=='
    
#- platform: broadlink
#  host: 192.168.2.60
#  mac: '34:EA:34:F6:40:87'
#  type: sp3
#  friendly_name: "Abajur Pedro Henrique"
#  icon: mdi:power-socket
 

- platform: broadlink
  host: 192.168.2.76
  mac: '34:EA:34:B2:EA:81'
  type: rm_mini
  timeout: 5
  switches:
    ar_con_16:
      friendly_name: Ar Condicionado 16
      command_on: 'JgDyABMAAk5iAAEnEQ8QMhAREBEPEhARDxEPEg8SDzIQERAREDEQERARDzIQMRAyEDERMhAQDxIPEg8RDxIQERARDxEQERAREBAQERAREBEPERASDxIPEQ8SDxIPEQ8SDxIQEQ8REBEQERAQEBEQERARDxEQMhAyEDEPMxBiYgABJxAyERAPERAREBEQEBAREBEQEQ8yEBIPEQ8zDzIPMhAyEBEQMRAyEDEQMRAyEDIPMw8yDxIPERAREDIPMhAxEBEQERARDxEQEhAREBAPEg8SDzIPEhARDxEQMhAQEBEQERARDxEQERAREDIPMg8zDzIQAA0FAAAAAAAA=='
      command_off: ''
      
    ar_controle:
      friendly_name: Controle Ar Condicionado
      command_on: 'JgBoARUAAklkAAElEg8SLxIPEg8SDxEQERAQEBEQETEQEBIPEi8SDxIPEi8SMBIvEjEQMRAREBAREBEQEBASDxIPEg8SDhIPEg8SDhIPEg8SDxIPERAREBEPERAREBAQERASDxIPEg4SDxIPEg4SDxIPEg8RMBIwETERMBJgZQABJRIvEg8SDxIOEg8SDxIOEg8SDxIwERAREBEwERAQMRIwEi8SLxIwEi8SDxIPEg8REBEQEQ8REBEQEBERDxIPEg8SDhIPEg8SDxEPEg8SDxIOEhAREBEPEg8REBAREBAREBIPEg4SDxIPEg8SDhIPEg8SYWMAASUSMBIPERAREBEPERAREBIPEQ8SMBIOEg8SLxMOEjASMBEQETAPMhExEi8SMBIvEjASLxIPEg8SDxExETAPMhIPEg8SDxIOEg8SDxIOEg8SDxIvEjASDxExEQ8REBIwEQ8SDxIPEg4SDxIwEi8SLxIwEQANBQ=='
      command_off: 'JgBoARMAAkxhAAEnEBEQMRAREBEQEQ8SDxIPEQ8SDzMPERAREDEQMhAREDEQMg8yEDIPMw8RDxIPEhARDxEQERAREBAQERAREBAQERAREBEQEBASDxIPEQ8SDxIPEg8REBEQERAQEBEQERARDxEQERAREBAQERASDzIPMw9jYgABJxAxEBEQERAREBAQERAREBAQERAyDxIPEg8yDxIPMg8zEDEQMhAxEDIPERAREBEQEQ8SDxIPEQ8SDxIPEg8REBEQERAQEBEQERAREBAQERAREBEPERASDxEQEQ8SDxIPERAREBEQEQ8REBEQERAQEBEQYmIAASgQMRERDxEPEg8SDxEPEg8SEBEQMRAREBAQMhAxEDIQMRASDzIPMw8yEDEQMhAxEDIQMRAREBEPERAzDzIPMg8SDxIQERAQEBEQERAQEBEQERAxETEQEQ8zDxEQEQ8zDxEQERAREBAQERAREBEPMhAyDwANBQ=='
 
    ar_ventila:
      friendly_name: Ar Condicionado Ventilar
      command_on: 'JgDyABMAAk5hAAEoEBEPMg8SDxIPEg8REBEQERAQEDIQERAQEDIQEQ8REDMPMg8yDzMQMRAREBEQEBAREBEQEBAREBEQERARDxIPEg8RDxIPEg8SDxEQERAREBAQERAREBEPERAREBEQEBAREBIPEQ8SDxIPMhAyEDEQMg9jYgABJxEwEBEQERAREBEPEg8SDxEPEg8yDxIQERAREBAQMhAxEBEQMRAyEDIQMg8yDzIQMhAxEBEQERAQEDIQMRAyEBEPEg8SDxEPEg8SEBEPERAyEDEQERAxEBEQMRAyEBEPEg8SDxIPEQ8SDzIQMhAxEDIQAA0FAAAAAAAA=='
    
    ar_auto:
      friendly_name: Ar Condicionado Automatico
      command_on: 'JgDyABMAAk9jAAElEg8SMA8REg8SDxARERAREA8REjARDxIPEjAQEBAREDIPMhAxEDIQMg8SERARDxIPEg8PERAREBEQEQ8REBEQERAQEBEQERARDxEQEg8SEQ8PEhIPEQ8QERAREBEPERAREBEQEBAREBEQMRAyEDIRMBBiYwABJxIvEg8QEREPEg8SDxAREQ8SDxIwEQ8SEBEPERASMBEwEg8SLxIwEi8SMBEwEi8SMREwDxIREA8REjASLxMuEw4SDxIPEg4SDxMvETESDhAREjAPERIwEi8SDxMOEg4SDxMOEg8SDhIPEjARMQ8yDzMSAA0FAAAAAAAA=='

    ar_cont_doctor:
      friendly_name: Ar Condicionado Doctor
      command_on: 'JgDyABIAAj5iAAEnERAQMRAREBEQEBASDxIPEQ8SDzMPERAREDEQERAREDEQMhAxEDIPMxARDxEPEg8SDxEQERAREBEQEBAREBEQEBAREBEQEQ8REBIPEg8RDxIPEg8RDxIQERAREBAQERAREBAQERAREBEQMRAyEDIPMhBiYgABKBAxEBEQEQ8REBEQERAQEBEQERAxEBIPEg8yDxIPMhAyDxEQMhAxEDIPMhAyDzMQMQ8zDzIQMRAREDIQMRAxEBEQERAREBAQEg8SDxEPEg8SDzIQERAREBAQMhAQEBEQERAREBAQERAREDIQMQ8zDzIQAA0FAAAAAAAA=='
      command_off: 'JgDyABMAAkliAAEnERAQMRAREBEQEBASDxIPEQ8SDzIQERAREDEQERAREDEQMhAxEDIPMw8REBEPEg8SDxEQERAREBAQERAREBEQEBAREBEQEQ8REBIPEg8RDxIPEg8REBEQERARDxEQERAREBAQERAREBEPMhAyEDIPMhBiYgABKA8yEBEQEBAREBEQERAQEBEQERAxEBIPERARDxIPMhAyEBAQMhAxEDIQMRAyEDEQMg8zDxEQEQ8SEDEQMhAxEBEQERAQEBEQERARDxIPEg8yDzMPERAyEBAQMhAxEBEQERARDxEQERAREDIQMQ8zDzIQAA0FAAAAAAAA=='
      
    ar_turbo:
      friendly_name: Ar Condicionado Turbo
      command_on: 'JgDyABIAAj5iAAEnERAQMRAREBEQEBASDxIPEQ8SDzMPERAREDEQERAREDEQMhAxEDIPMxARDxEPEg8SDxEQERAREBEQEBAREBEQEBAREBEQEQ8REBIPEg8RDxIPEg8RDxIQERAREBAQERAREBAQERAREBEQMRAyEDIPMhBiYgABKBAxEBEQEQ8REBEQERAQEBEQERAxEBIPEg8yDxIPMhAyDxEQMhAxEDIPMhAyDzMQMQ8zDzIQMRAREDIQMRAxEBEQERAREBAQEg8SDxEPEg8SDzIQERAREBAQMhAQEBEQERAREBAQERAREDIQMQ8zDzIQAA0FAAAAAAAA=='
      command_off: 'JgDyABMAAj5hAAEoEBAQMhARDxEQERASDxEPEg8SDzIQERARDzIQERAQEDIQMRAyEDEQMhARDxIPEg8REBEQERAQEBEQERAREBAQERAREBAQERAREBEQEQ8SDxIPERAREBEQEBAREBEQERAQEBEQERAQEBEQMhAyEDEPMxBiYgABJxAyEBAQERAREBEQEBAREBEQEBMvEBEQEQ8zDzIQMRAyEg8QMRAxEDIQMRAyEDIQMQ8zDxIPERAREDEQMhAxEBEQERARDxEQERAREBEQEQ8SDzIPEhAQEBEQMhAQEBEQERAQEBEQERAREDIQMQ8zDzIQAA0FAAAAAAAA=='
 
 
 
- platform: broadlink
  host: 192.168.2.72
  mac: '34:EA:34:C6:E6:FA'
  type: mp1
  friendly_name: 'MP1'
  slots:
    slot_1: 'Receptor'
    slot_2: 'ChromeCast'
    slot_3: 'TV LG'
    slot_4: 'Reserva'

- platform: tplink
  host: 192.168.2.71
  mac: '50:C7:BF:05:FB:F3'
  name: "Tomada Ar"
  
- platform: broadlink
  host: 192.168.2.60
  mac: '34:EA:34:F6:40:87'
  type: sp3
  friendly_name: "Tomada Quarto Casal"
  icon: mdi:power-socket
  
- platform: broadlink
  host: 192.168.2.73
  mac: '34:EA:34:B8:1D:F6'
  type: sp3
  friendly_name: "Tomada Quarto Filho"
  icon: mdi:power-socket
  

  
- platform: orvibo
  switches:
    - host: 192.168.2.79
      mac: AC:CF:23:8D:B6:46
      name: 'Geladeira'